---
title: "Mediation Summary"
author: "Brian S. Yandell"
date: "4/18/2018"
output: html_document
params:
  suffix:
    value: mediation
    label: File suffix
  batch:
    value: ../results
    label: Batch directory
  cutoff:
    value: 0.05
    label: P-value cutoff
  driver:
    value: med
    label: driver choice
  probtype:
    value: allele
    label: Genotype Probability Type
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(dplyr)
library(ggplot2)
```

These analyses were run with SLURM using the following setup:

- causal drivers for mediators
    + mediators selected based on peak LOD near target peak LOD
    + drivers selected as best SNPs for mediators
- using 3-level SNP (from 36 allele pair probabilities) for SNP analysis
- use 0.05 cutoff for summary

```{r}
(driver <- params$driver)
(probtype <- params$probtype)
folder <- paste("best", driver, probtype, sep = "_")
filenames <- list.files(file.path(params$batch, folder))
targets <- stringr::str_remove(filenames, paste0("_", driver, ".*"))
chrs <- stringr::str_extract(targets, "[0-9]+$")
targets <- stringr::str_remove(targets, "_[0-9]+$")
filenames <- as.list(file.path(params$batch, folder, filenames))
names(filenames) <- targets
```

```{r}
meds <- 
  dplyr::bind_rows(
    purrr::map(
      filenames,
      function(fname) {
        dplyr::rename(
          dplyr::mutate(
            dplyr::select(
              dplyr::bind_rows(
                purrr::map(
                  as.list(fname),
                  function(x) 
                    dplyr::filter(
                      read.csv(
                        x,
                        row.names = NULL,
                        stringsAsFactors = FALSE),
#                      triad == "causal",
                      pvalue <= params$cutoff))),
              symbol, chr, pos, mediation, pvalue, dplyr::everything()),
            mediation = mediation / log(10),
            chr = factor(chr, c(1:19, "X")),
            LRmed = LRmed / log(10),
            pvalue = pmax(pvalue, 1e-10)),
          QTLs = "info",
          lod_adj = "mediation",
          mediator = "symbol",
          lod_med = "LRmed")
      }),
    .id = "target")
```

Need to relate this to the peaks file.

```{r}
tmpfn <- function(group) {
  wh <- which(!is.na(group))
  ct <- diff(c(wh, length(group) + 1))
  rep(group[wh], ct)
}

peaks <- 
  dplyr::rename(
    dplyr::arrange(
      dplyr::mutate(
        readxl::read_excel(
          "../data/Ex vivo peak summary with QTL count[1].xlsx",
          col_types = c(rep("text", 2), rep("numeric", 12), "numeric")),
        chr = factor(chr, c(1:19, "X")),
        QTL = tmpfn(QTL)),
      dplyr::desc(lod)),
    target = "lodcolumn",
    pos_tar = "pos",
    lod_tar = "lod",
    group = "QTL")
```

```{r}
meds <- 
  dplyr::left_join(meds, peaks, by = c("target", "chr"))
```

```{r}
write.csv(meds %>%
            select(target:pvalue, id:lod_med, nearest_marker:ci_hi, group) %>%
            rename(QTL = "group"),
          file = file.path(params$batch,
                           paste0(params$suffix, "_best_", driver, "_", probtype, ".csv")))
```

```{r}
tmpfn <- function(chr, group) {
  factor(unlist(sapply(split(group, chr), function(x) 1 + x - min(x))))
}
```

```{r}
meds <- 
  dplyr::mutate(
    dplyr::arrange(
      meds,
      group),
    chr = factor(chr, unique(chr)),
    chrGroup = tmpfn(chr, group))
```

### Plots

```{r}
ggplot2::ggplot(meds) +
  ggplot2::aes(lod_tar - lod_adj, -log10(pvalue),
               col = chrGroup) +
  ggplot2::geom_point(alpha = 0.5) +
  ggplot2::facet_wrap(~ chr)
```

```{r}
ggplot2::ggplot(meds) +
  ggplot2::aes(pos_tar, pos, col = chrGroup) +
  ggplot2::geom_abline(slope=1, intercept=0, col="grey") +
  ggplot2::geom_point(alpha = 0.5) +
  ggplot2::facet_wrap(~ chr)
```

```{r fig.width=9,fig.heigth=6}
ggplot2::ggplot(meds) +
  ggplot2::aes(pos_tar, lod_tar - lod_adj, col = chrGroup, symbol = mediator) +
  ggplot2::geom_point(alpha = 0.5) +
  ggplot2::facet_wrap(~ chr)
```

```{r}
knitr::knit_exit()
```

# Mediation effects

```{r}
folder <- paste("fit", driver, probtype, sep = "_")
filenames <- list.files(file.path(params$batch, folder))
targets <- stringr::str_remove(filenames, paste0("_", driver, ".*"))
chrs <- stringr::str_extract(targets, "[0-9]+$")
targets <- stringr::str_remove(targets, "_[0-9]+$")
filenames <- as.list(file.path(params$batch, folder, filenames))
names(filenames) <- paste(targets, chrs, sep = "_")
```

```{r}
effects <- 
  dplyr::mutate(
    dplyr::rename(
      dplyr::bind_rows(
        purrr::map(
          filenames,
          function(x) 
            read.csv(
              file.path(params$batch, x),
              row.names = NULL,
              stringsAsFactors = FALSE)),
        .id = "target"),
      lod = "LR"),
    lod = lod / log(10))
```

```{r}
write.csv(effects %>%
  filter(response == "target") %>%
  distinct(target, .keep_all = TRUE),
  file = file.path(params$batch,
                   paste0("target", "_fit_", driver, "_", probtype, ".csv")))
```

```{r}
write.csv(effects %>%
  filter(response == "mediator"),
  file = file.path(params$batch,
                   paste0("mediator", "_fit_", driver, "_", probtype, ".csv")))
```

```{r}
write.csv(effects %>%
  filter(response == "mediation"),
  file = file.path(params$batch,
                   paste0("adjusted", "_fit_", driver, "_", probtype, ".csv")))
```


