---
params:
  target_name:
    label: Target
    value: AA_G83_ins_secrete_gm
  chr_id:
    label: Chromosome
    value: 1
  minpvalue:
    label: Minimum p-value
    value: 0.05
  dataSetup:
    choices:
    - dataJax.R
    - dataMadison.R
    - dataJaxMadison.R
    input: select
    label: Data setup file
    value: dataJaxMadison.R
  resultpath:
    input: text
    label: Path to put CSV results (none if '')
    value: ../results
  datapath:
    input: text
    label: Path to derived data (required for Madison)
    value: ../data
---

---
title: Summary for Target `r params$target_name` Chr `r params$chr_id`
author: "Brian S. Yandell"
date: "`r  format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
})
```

```{r}
target_name <- params$target_name
chr_id <- as.character(params$chr_id)
datapath <- params$datapath
resultpath <- params$resultpath
```

Summary of mediators for target `target_name` on chromosome `r chr_id`. These have been run through `intermediate::mediate_qtl2` to get best region for causal inference.

```{r}
target_index <- 
  readRDS(
    file.path(
      resultpath,
      target_name,
      paste0(target_name, "_", chr_id, "_med_qtl2.rds")))
```

```{r eval=FALSE}
# Updates due to shifing code base.
target_index <-
  purrr::map(
    target_index,
    function(x) {
      m <- match("^driver$", names(x))
      if(!is.na(m)) names(x)[m] <- "driver_names"
      m <- match("^driver$", names(x$best))
      if(!is.na(m)) names(x$best)[m] <- "driver_names"
      x
    })
class(target_index) <- c("listof_mediation_index", class(target_index))
saveRDS(target_index, 
        file = file.path(resultpath,
                         target_name,
                         paste0(target_name, "_", chr_id, "_med_qtl2.rds")))
```

```{r}
intermediate::ggplot_listof_mediation_index(target_index)
```

```{r}
(calls <- 
  apply(
    sapply(
      target_index,
      function(x) table(x$best$triad[x$best$pvalue <= params$minpvalue])),
    1, function(x) sum(x>0)))
```

```{r}
i <- names(calls[1]) # "causal"
if(calls[i]) {
  p <- intermediate::ggplot_listof_mediation_index(
    target_index, i, params$minpvalue)
  if(!is.null(p))
    plotly::ggplotly(p)
}
```

```{r}
i <- names(calls[2]) # reactive
if(calls[i]) {
  intermediate::ggplot_listof_mediation_index(
    target_index, i, params$minpvalue)
}
```

```{r}
i <- names(calls[3]) # independent
if(calls[i]) {
  intermediate::ggplot_listof_mediation_index(
    target_index, i, params$minpvalue)
}
```

```{r}
i <- names(calls[4]) # undecided
if(calls[i]) {
  intermediate::ggplot_listof_mediation_index(
    target_index, i, params$minpvalue)
}
```

Best SNPs are output to file `r paste0(target_name, "_", chr_id, "_", "_topsnps.csv")`.

```{r}
write.csv(
  intermediate::bind_mediation_index(target_index)$best %>%
    select(-lod) %>%
    rename(lod = "LR") %>%
    mutate(lod = lod / log(10)),
  file = file.path(
    resultpath, 
    target_name,
    paste0(target_name, "_", chr_id, "_", "_topsnps.csv")))
```
