---
title: "Mediation Summary"
author: "Brian S. Yandell"
date: "4/18/2018"
output: html_document
params:
  suffix:
    value: "mediation"
    label: File suffix
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Ideas for further improvements:

- 3-level SNP
- M-P-D allele plot (add CCcolors and Rcolorbrewer colors for SNPs)
- use CI region rather than offset (range is 0.2 to >50, so nix this)
- organize other info from annot

```{r}
filenames <- list.files("batch", paste0("_", params$suffix, ".csv"))
names(filenames) <- stringr::str_replace(filenames, paste0("_", params$suffix, ".csv"), "")
filenames <- as.list(filenames)
```

```{r}
meds <- 
  dplyr::rename(
    dplyr::mutate(
      dplyr::select(
        dplyr::bind_rows(
          purrr::map(
            filenames,
            function(x) 
              dplyr::filter(
                read.csv(
                  paste0("batch/", x),
                  stringsAsFactors = FALSE),
                triad == "causal",
                pvalue <= 0.1)),
          .id = "pheno"),
        pheno, symbol, chr, pos, mediation, pvalue, dplyr::everything()),
      mediation = mediation / log(10),
      chr = as.character(chr),
      LRmed = LRmed / log(10)),
    QTLs = "info",
    lod_med = "LRmed")
```

Need to relate this to the peaks file.

```{r}
tmpfn <- function(QTL) {
  wh <- which(!is.na(QTL))
  ct <- diff(c(wh, length(QTL) + 1))
  rep(QTL[wh], ct)
}
```

```{r}
peaks <- 
  dplyr::rename(
    dplyr::arrange(
      dplyr::mutate(
        readxl::read_excel(
          "local/Jax/Ex vivo peak summary with QTL count[1].xlsx",
          col_types = c(rep("text", 2), rep("numeric", 12), "numeric")),
        QTL = tmpfn(QTL)),
      dplyr::desc(lod)),
    pheno = "lodcolumn",
    peak_pos = "pos",
    peak_lod = "lod")
m <- match(LETTERS[1:8], names(peaks))
names(peaks)[m] <- paste0(LETTERS[1:8], "_p")
```

```{r}
out <- 
  dplyr::left_join(meds, peaks, by = c("pheno", "chr"))
```

```{r}
write.csv(out, file = paste0(params$suffix, "Summary.csv"))
```


### Plots

```{r}
out <- 
  dplyr::mutate(
    dplyr::arrange(
      out,
      QTL),
    chr = factor(chr, unique(chr)),
    chrQTL = paste(chr, QTL, sep = ":"),
    chrQTL = factor(chrQTL, unique(chrQTL)))
```

```{r}
ggplot2::ggplot(out) +
  ggplot2::aes(peak_lod - mediation, -log10(pvalue), col = chrQTL) +
  ggplot2::geom_point() +
  ggplot2::facet_wrap(~ chr)
```

```{r}
ggplot2::ggplot(out) +
  ggplot2::aes(peak_pos, pos, col = chrQTL) +
  ggplot2::geom_abline(slope=1, intercept=0, col="grey") +
  ggplot2::geom_point() +
  ggplot2::facet_wrap(~ chr)
```

```{r fig.width=9,fig.heigth=6}
plotly::ggplotly(ggplot2::ggplot(out) +
  ggplot2::aes(peak_pos, peak_lod - mediation, col = chrQTL, symbol = symbol) +
  ggplot2::geom_point() +
  ggplot2::facet_wrap(~ chr))
```

```{r}
if(params$suffix == "mediation_snp")
  knitr::knit_exit()
```

### Plot of allele means

```{r}
allele_fit <- function(out) {
  out1 <- 
    dplyr::arrange(
      dplyr::ungroup(
        dplyr::mutate(
          dplyr::group_by(
            dplyr::mutate(
              tidyr::gather(
                dplyr::select(
                  out,
                  pheno, QTL, symbol, pvalue, A_m:H_m, A:H, A_p:H_p),
                allele, effect, -pheno, -QTL, -symbol, -pvalue),
              fitType = stringr::str_remove(allele, "[A-H]_*"),
              allele = stringr::str_remove(allele, "_[a-z]"),
              fitType = ifelse(fitType == "", "a", fitType),
              fitType = c(m="Mediator", p="Target", a="Adjusted")[fitType],
              fitType = factor(fitType, c("Mediator", "Target", "Adjusted"))),
            pheno, QTL, symbol, fitType),
          effect = effect - mean(effect))),
      pvalue)
  class(out1) <- c("allele_fit", class(out1))
  out1
}
```

```{r}
ggplot_allele_fit <- function(out1) {
  # This is broken now.
  out1 <- 
    dplyr::mutate(
      dplyr::filter(
        dplyr::mutate(
          out1,
          symbol = paste0(symbol, " (", signif(pvalue, 2), ")")),
        symbol %in% unique(symbol)[1:12]),
      symbol = factor(symbol, unique(symbol)))
  ggplot2::ggplot(out1) +
    ggplot2::aes(fitType, effect, color = allele, group = allele) +
    ggplot2::geom_line() +
    ggplot2::geom_point(size=2) +
    ggplot2::facet_wrap(~ symbol) +
    ggplot2::ggtitle(paste(out1$pheno[1], "for QTL", out1$QTL[1]))
}
autoplot.allele_fit <- function(...) ggplot_allele_fit(...)
```

```{r}
outp <- split(out, interaction(out$pheno, out$QTL, drop = TRUE))
allele_fits <- purrr::map(outp, allele_fit)
```

```{r fig.width = 12, fig.heigth = 9}
sapply(allele_fits, function(x) print(ggplot_allele_fit(x)))
```

